services:
  - type: web
    name: flask-webhook
    env: python
    buildCommand: 'pip install -r requirements.txt'
    startCommand: 'gunicorn app:app'
    autoDeploy: true
    region: oregon
    branch: main
